services:
  - type: web
    name: honest-voice
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    dockerCommand: bundle exec puma -C config/puma.rb
    region: oregon
    plan: free
    healthCheckPath: /
    envVars:
      - key: RAILS_ENV
        value: production
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: RAILS_LOG_TO_STDOUT
        value: "1"
      - key: RAILS_SERVE_STATIC_FILES
        value: "1"
